version: "3.8"
services:
  db:
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: task1

    image: postgis/postgis:15-3.5-alpine
    container_name: postgres_db
    restart: always
    ports:
      - "5432:5432"

  api:
    build: .
    container_name: fastapi_app
    depends_on:
      db:
        condition: service_started
    ports:
      - "8000:8000"
